package com.example.accessingdatamysql;

import io.opentelemetry.api.GlobalOpenTelemetry;
import io.opentelemetry.api.common.Attributes;
import io.opentelemetry.api.metrics.LongCounter;
import io.opentelemetry.api.metrics.Meter;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.HttpStatus;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.server.ResponseStatusException;

import javax.security.sasl.AuthenticationException;
import java.io.IOException;
import java.net.HttpURLConnection;
import java.net.URL;
import java.util.Map;

import static io.opentelemetry.semconv.trace.attributes.SemanticAttributes.HTTP_METHOD;
import static io.opentelemetry.semconv.trace.attributes.SemanticAttributes.HTTP_ROUTE;

@Controller    // This means that this class is a Controller
@RequestMapping(path = "/demo") // This means URL's start with /demo (after Application path)
public class MainController {
	public static final String USERNAME_HEADER = "username";
	private final Logger log = LoggerFactory.getLogger(MainController.class);


	@Autowired // This means to get the bean called userRepository
	// Which is auto-generated by Spring, we will use it to handle the data
	private UserRepository userRepository;
	private final Meter meter;
	private final LongCounter requestCounter;

	public MainController(UserRepository userRepository) {
		this.userRepository = userRepository;

		meter = GlobalOpenTelemetry.getMeter(MainController.class.getSimpleName());
		requestCounter = meter.counterBuilder("my.request.count").build();
	}

	private void recordGetRequest(String httpRoute) {
		Attributes counterAttributes = Attributes.of(
				HTTP_METHOD, "GET",
				HTTP_ROUTE, httpRoute
		);
		requestCounter.add(1, counterAttributes);
	}

	@PostMapping(path = "/add") // Map ONLY POST Requests
	public @ResponseBody String addNewUser(@RequestParam String name
			, @RequestParam String email) {
		recordGetRequest("/add");
		// @ResponseBody means the returned String is the response, not a view name
		// @RequestParam means it is a parameter from the GET or POST request

		User n = new User();
		n.setName(name);
		n.setEmail(email);
		userRepository.save(n);
		return "Saved";
	}

	@GetMapping(path = "/all")
	public @ResponseBody Iterable<User> getAllUsers(@RequestHeader(USERNAME_HEADER) String username) {
		recordGetRequest("/all");

		try {
			URL url = new URL("http://localhost:8080/demo/auth");
			HttpURLConnection con = (HttpURLConnection) url.openConnection();

			con.setRequestProperty(USERNAME_HEADER, username);

			int responseCode = con.getResponseCode();

			if (responseCode != 200) {
				throw new AuthenticationException("Could not authenticate. Authentication server returned " + responseCode);
			}
		} catch (IOException e) {
			// wrap the exception into an internal server error exception.
			throw new ResponseStatusException(HttpStatus.INTERNAL_SERVER_ERROR, "Error in authorization service", e);
		}

		log.info("authentication successful, retrieving data from database.");
		// This returns a JSON or XML with the users
		return userRepository.findAll();
	}

	@GetMapping(path = "/auth")
	public @ResponseBody void authenticate(@RequestHeader Map<String, String> headers) {
		recordGetRequest("/auth");
		if (!headers.containsKey(USERNAME_HEADER)) {
			throw new ResponseStatusException(HttpStatus.BAD_REQUEST, String.format("request is missing '%s' header.", USERNAME_HEADER));
		}
		String myHeader = headers.get(USERNAME_HEADER);

		// some work happening here
		try {
			Thread.sleep(300);

			if (myHeader.contains("@")) {
				Thread.sleep(600);
				log.error("Unexpected character '@' in username.");
				throw new IllegalArgumentException("Unexpected input");
			}
		} catch (InterruptedException e) {
			// no need to handle, just for simulating work.
		} catch (IllegalArgumentException e) {
			// wrap the exception in a response status exception with error code 500.
			throw new ResponseStatusException(HttpStatus.INTERNAL_SERVER_ERROR, "error during authentication", e);
		}
	}
}
